### ISSUE TITLE
[Error] Could not find or access 'ipxe.j2' 

### ISSUE THREAD

**Issue by DirectedSoul1** [rh-ecosystem-edge/ansible-ai-playbook#10]
While using `setup-pxe` role, under the task `install.yml` , seeing an error as below |

```
   "msg": "Could not find or access 'ipxe.j2'\nSearched in:\n\t/root/ansible-ai-playbook/roles/setup-pxe/templates/ipxe.j2\n\t/root/ansible-ai-playbook/roles/setup-pxe/ipxe.j2\n\t/root/ansible-ai-playbook/roles/setup-pxe/tasks/templates/ipxe.j2\n\t/root/ansible-ai-playbook/roles/setup-pxe/tasks/ipxe.j2\n\t/root/ansible-ai-playbook/templates/ipxe.j2\n\t/root/ansible-ai-playbook/ipxe.j2 on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
```

While inspecting the role, 

```
└── setup-pxe
    ├── defaults
    │   └── main.yml
    ├── handlers
    │   └── main.yml
    ├── tasks
    │   ├── dhcp.yml
    │   ├── install.yml
    │   ├── main.yml
    │   └── tftp.yml
    └── templates
        ├── dhcpd.conf.j2
        ├── pxeboot.conf.j2
        └── tftp.service.j2
```
and the task `install.yml` calls this file `ipxe.j2` which doesn't exist. 

```
  - name: setup iPXE config
  template:
    src: ipxe.j2
    dest: "{{ HTTP_DIR }}/ipxe"
  become: yes
  when: IPXE is true
```
