### ISSUE TITLE
[Error] While using `download-iso-pxe` role

### ISSUE THREAD

**Issue by DirectedSoul1** [rh-ecosystem-edge/ansible-ai-playbook#8]
While the user specifies the `discovery.iso` in his system, extracting of this ISO results in an error as shown

```
fatal: [localhost]: FAILED! => {
  
            "image": "/tmp/download-iso-pxe/discovery_image_testcluster1.iso"
        }
    },
    "msg": "Directory '/var/lib/tftpboot' does not exist"
}
```

`playbook.yml` has 

```
---
- hosts: localhost
  roles:
    - download-iso-pxe
  vars:
    ARCH: x86
    URL: http://<ipv4-ip>:8080
    CLUSTER_ID: "*********"
    ISO_NAME: "discovery_image_testcluster1.iso"
    HTTP_DIR: "/var/www/html/pxe"
```
